version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3036:3036
    network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
