version: '3.1'

services:
  app:
    image: notnottimothy77/ecommerce-app
    command: "bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node /app/server.js'"
    ports:
      - 80:8080
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appWorker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
